name: Docker Image CI

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: vite_testing
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker metadata for viewer
        id: meta_viewer
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/tournamentviewer
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build & Push viewer
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_viewer.outputs.tags }}
          labels: ${{ steps.meta_viewer.outputs.labels }}
          secrets: |
            vite_api_base_url=${{ secrets.VITE_API_BASE_URL }}
